name: Pull-request

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Need all history to set the correct modified dates
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: 'caseware'
      - name: Set correct modified dates
        run: |
          git ls-tree -r --name-only HEAD | while read filename; do
          unixtime=$(git log -1 --format="%at" -- "${filename}")
          touchtime=$(date -d @$unixtime +'%Y%m%d%H%M.%S')
          touch -t ${touchtime} "${filename}"
          done
      - name: Set private.pem
        run: echo '${{ secrets.REPORT_PRIVATE_KEY }}' > private.pem
      - name: Evaluate report.enc
        run: npx @caseware/provider-bindings-tests evaluate
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CWI_SECRET_GITHUB_TOKEN_DISTRIBUTOR }}
      - run: yarn install --prod
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CWI_SECRET_GITHUB_TOKEN_DISTRIBUTOR }}
